name: Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the issue
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: dropdown
    id: nameless_version
    attributes:
      label: NamelessMC Version
      description: From StaffCP -> Overview
      options:
        - 2.0.x
        - <= 2.0.0-pr13
    validations:
      required: true

  - type: dropdown
    id: tailpad_version
    attributes:
      label: TailPad Version
      description: From StaffCP -> TailPad -> Updates
      options:
        - <= 0.0.x
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: "Steps to reproduce the behaviour."
      placeholder: "1. Go to '...'

        2. Click on '....'

        3. Scroll down to '.....'

        4. See error"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behaviour
      description: What were you expecting to happen?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Desktop
      description: Please complete the following information.
      value: |
        - OS: [e.g. Windows]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]
    validations:
      required: false

  - type: textarea
    attributes:
      label: Smartphone
      description: Please complete the following information.
      value: |
        - Device: [e.g. iPhone6]
        - OS: [e.g. iOS8.1]
        - Browser [e.g. stock browser, safari]
        - Version [e.g. 22]
    validations:
      required: false

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Information
      description: Add more information about the problem if necessary.
    validations:
      required: false
